repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--safe]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v7.19.0'
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args: ['--fix']
        additional_dependencies:
          - eslint@7.19.0
          - eslint-config-prettier@7.2.0 # prettier used with eslint directly
          - eslint-plugin-prettier@3.3.1
          - typescript@4.1.4
          - prettier@2.2.1
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
