[build-system]
requires = [
    "setuptools>=44",
    "setuptools_scm[toml]>=3.4",
    "wheel>=0.30",
    "jupyter_packaging~=0.7.0",
    "jupyterlab~=3.0",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
known_first_party = ["ipydatagrid", "tests"]
line_length = 80

[tool.setuptools_scm]
write_to = "ipydatagrid/_version.py"
write_to_template = """
# Copyright (c) Bloomberg.
# Distributed under the terms of the Modified BSD License.

\"\"\" Version information \"\"\"
__version__ = "{version}"
"""

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "80"

[tool.black]
line-length = 88
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
